### ISSUE TITLE
Dialogs disappear on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [stovocor/whohasmystuff#22]
When I perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1. Click on "..." (More Options)
2. Click on Restore
3. Orientation Change

**Comment by trikaphundo** [comment]
Indeed, this happens for every dialog in the application.

I have been checking the code of the application and this happens due to the use of fragments.
To be more precise: every time a [configuration change](https://developer.android.com/guide/topics/resources/runtime-changes.html) occurs in Android the activity is recreated; normally Android restores most of the activity's state, but not all. This is the case for objects in general and fragments in particular.

If the dialog was called from an activity, it would "survive", that is, would be stored as part of the activity state. But since the dialogs are created from fragments and the fragments, in this application's source code, are recreated every time the activity is created, you just lose them.

In my opinion I see two solutions:
 -Drop the use of fragments -since in this application they are just used like regular activities-, this way is Android who will take care of reconstructing dialogs.
 -Write code to make dialogs "survive"; fragments can be thought of as "sub-activities", and so, they hold methods for managing the [fragments life-cycle](https://developer.android.com/guide/components/fragments.html?hl=en#Creating) in a very similar way as it is done with activities

**Comment by stovocor** [comment]
Thank you very much for the analysis and the proposed solution. What do you think about using a [DialogFragment](http://stackoverflow.com/a/15729764/991862) instead?

**Comment by trikaphundo** [comment]
Hallo! Yes, it is a good idea indeed. It saves all the dirty work of managing the dialog state in the fragment life-cycle methods, so I think it is just perfect.

Are you working on this? Just to avoid futile work on my part :)

**Comment by stovocor** [comment]
> Are you working on this? Just to avoid futile work on my part :)

No, currently I do not have the spare time. If you provide a pull request, I will be more than happy to integrate it. :)
